---
title: "Class Meetings"
#author: "Rebecca Lunsford"
subtitle: Fall 2018
---

Links to all slide decks and in-class lab materials will be posted here.

[Class Videos](https://mail.ohsu.edu/owa/redir.aspx?C=AuS0hQvbvb7A1w7nV44AaKgi4m2Y8ioWqIRmD-1k506XFBRsUSXWCA..&URL=https%3a%2f%2flogin.echo360.org%2flogin%3fappId%3dc08c41ee-50e3-45e8-a6e6-e9579b28f620%26afterLoginUrl%3d%2fhome).

```{r echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(knitr)
library(DT)
cm <- read_csv("cm.csv") %>%
  mutate(Date = ifelse(Month == "Week", paste0("<b>", Month, " ", Day, "</b>"), paste(Month, Day))) %>%
  mutate(`In-class Lab` = ifelse(lab == "-" | is.na(lab_link) | is.na(lab_link),
                                    lab,
                                    paste0("<a href='", lab_link, "'>", lab, "</a>"))) %>% 
  select(Weekday, Date, `CM / Block`, Topics, `In-class Lab`)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
if(knitr:::is_html_output()){
  cm %>% datatable(rownames = FALSE,
                         class = 'cell-border stripe',
                         filter = list(position = 'top'),
                         options = list(pageLength = nrow(cm), 
                                        autoWidth = TRUE,
                                        columnDefs = list(list(width = '300px', targets = c(3)),
                                                          list(width = '20px',  targets = c(0)) ),
                                        bInfo = FALSE,
                                        paging = FALSE),
                         escape = FALSE)
} else {
  knitr::kable(cm, booktabs = TRUE, longtable = TRUE)
}
```