\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Homework 3 - Key},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Homework 3 - Key}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \subtitle{Math 530/630}
  \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The longitudinal study
  \href{https://www.ncbi.nlm.nih.gov/pubmed/15531682}{\emph{Bone mass is
  recovered from lactation to postweaning in adolescent mothers with low
  calcium intakes}} examined total-body bone mineral content of young
  mothers during breast feeding and then in the postweaning period. We
  want to test the hypothesis that mothers gained more than 25 grams of
  bone mineral content in the postwearning period. The data for 10
  mothers is provided below; use a significance level of 0.05. The
  column \texttt{bf} stands for the first measurement (during
  breastfeeding). The column \texttt{pw} stands for the second
  measurement (during postweaning period). All values are in grams of
  bone density.

  \begin{enumerate}
  \def\labelenumii{\alph{enumii}.}
  \tightlist
  \item
    State the null and alternative hypotheses.
  \item
    First, do the test wrong: use an independent samples t-test, which
    ignores the paired nature of the dependent variables here, using the
    \texttt{t.test} function in R assuming equal variances. What would
    you conclude?
  \item
    Now, do the test right: use a dependent samples t-test (also known
    as a paired t-test), using the \texttt{t.test} function in R. Do you
    change your conclusions? Explain why or why not. In your discussion,
    you must reference the degrees of freedom of each test.
  \end{enumerate}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bones <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{mother=}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{,}
    \DataTypeTok{bf=}\KeywordTok{c}\NormalTok{(}\DecValTok{1928}\NormalTok{, }\DecValTok{2549}\NormalTok{, }\DecValTok{2825}\NormalTok{, }\DecValTok{1924}\NormalTok{, }\DecValTok{1628}\NormalTok{, }\DecValTok{2175}\NormalTok{, }\DecValTok{2114}\NormalTok{, }\DecValTok{2621}\NormalTok{, }\DecValTok{1843}\NormalTok{, }\DecValTok{2541}\NormalTok{),}
    \DataTypeTok{pw=}\KeywordTok{c}\NormalTok{(}\DecValTok{2126}\NormalTok{, }\DecValTok{2885}\NormalTok{, }\DecValTok{2895}\NormalTok{, }\DecValTok{1942}\NormalTok{, }\DecValTok{1750}\NormalTok{, }\DecValTok{2184}\NormalTok{, }\DecValTok{2164}\NormalTok{, }\DecValTok{2626}\NormalTok{, }\DecValTok{2006}\NormalTok{, }\DecValTok{2627}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Remember, the two-sample test is inappropriate.}
\KeywordTok{t.test}\NormalTok{(bones}\OperatorTok{$}\NormalTok{pw, bones}\OperatorTok{$}\NormalTok{bf, }\DataTypeTok{mu=}\DecValTok{25}\NormalTok{, }\DataTypeTok{alternative=}\StringTok{"greater"}\NormalTok{, }\DataTypeTok{var.equal =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Two Sample t-test
## 
## data:  bones$pw and bones$bf
## t = 0.44948, df = 18, p-value = 0.3292
## alternative hypothesis: true difference in means is greater than 25
## 95 percent confidence interval:
##  -205.6358       Inf
## sample estimates:
## mean of x mean of y 
##    2320.5    2214.8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# this is the right test}
\KeywordTok{t.test}\NormalTok{(bones}\OperatorTok{$}\NormalTok{pw, bones}\OperatorTok{$}\NormalTok{bf, }\DataTypeTok{mu=}\DecValTok{25}\NormalTok{, }\DataTypeTok{paired =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{alternative=}\StringTok{"greater"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Paired t-test
## 
## data:  bones$pw and bones$bf
## t = 2.4575, df = 9, p-value = 0.01815
## alternative hypothesis: true difference in means is greater than 25
## 95 percent confidence interval:
##  45.50299      Inf
## sample estimates:
## mean of the differences 
##                   105.7
\end{verbatim}

\newpage

Answers

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\item
  \begin{itemize}
  \tightlist
  \item
    Null hypothesis: Mothers gained less than or equal to 25 grams of
    bone mineral content.
  \item
    Alternative hypothesis: Mothers gained more than 25 grams of bone
    mineral content.
  \end{itemize}
\item
  As the p-value is greater than our alpha (e.i., 0.3292 \textgreater{}
  0.05), we fail to reject the null hypothesis.
\item
  Running the appropriate test, we now have a p-value of 0.01815, which
  is less than our alpha (0.05). Thus, we reject the null hypothesis.
  The degress of freedom for the un-paired t.test is 18 (n1 + n2 - 2),
  whereas the degrees of freedom for the paired t.test is 9 (n/2-1).
  Although this higher degrees of freedom does mean a lower critical
  value for the un-paired t.test making it ``easier'' to reach
  statistical significance at the aplha=0.05 level, it also means that
  the standard error will be inflated. As the standard error is in the
  denominator of the t-statistic calcuation, this inflated standard
  error results in a smaller t-statistic, making it ``harder'' to reach
  statistical significance.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Your office mate ran an experiment with \emph{N}=50 to test the
  hypothesis that her sample would have a mean different from the
  population mean, \(\mu\)=0, previously found by her advisor. She
  conducted a one-sample \emph{t} test with \(\alpha\)=.05 (two-tailed),
  and reported the 95\% confidence interval for \(\mu\) of variable
  \emph{X} is (8.979, 10.349). Note which of the following must also be
  true:
\end{enumerate}

Answers

\begin{verbatim}
* Null hypothesis: The sample mean is the same as the population mean of 0.
* Alternate hypothesis: $\mu$ is not equal to 0.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#First, let's look at some important numbers.}

\NormalTok{pop_mean <-}\StringTok{ }\DecValTok{0} \CommentTok{#population mean}
\NormalTok{n <-}\StringTok{ }\DecValTok{50}
\NormalTok{df <-}\StringTok{ }\NormalTok{n}\OperatorTok{-}\DecValTok{1} \CommentTok{#degrees of freedom}
\NormalTok{critical_value <-}\StringTok{ }\KeywordTok{qt}\NormalTok{(.}\DecValTok{975}\NormalTok{, }\DecValTok{49}\NormalTok{) }\CommentTok{#critical value in b.}
\NormalTok{mu <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\FloatTok{8.979} \OperatorTok{+}\StringTok{ }\FloatTok{10.349}\NormalTok{)}\OperatorTok{/}\DecValTok{2} \CommentTok{# sample mean}
\NormalTok{sd <-}\StringTok{ }\NormalTok{(}\FloatTok{10.339}\OperatorTok{-}\FloatTok{8.979}\NormalTok{)}\OperatorTok{/}\FloatTok{1.96} \CommentTok{# sample standard deviation }
\NormalTok{t_statistic <-}\StringTok{  }\NormalTok{(mu}\OperatorTok{-}\NormalTok{pop_mean)}\OperatorTok{/}\NormalTok{(sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(}\DecValTok{50}\NormalTok{))}
\NormalTok{p_value <-}\StringTok{ }\DecValTok{2}\OperatorTok{*}\KeywordTok{pt}\NormalTok{(t_statistic, df, }\DataTypeTok{lower=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "critical value:  2.00957523712924"
\end{verbatim}

\begin{verbatim}
## [1] "sample mean:  9.664"
\end{verbatim}

\begin{verbatim}
## [1] "sample standard deviation:  0.693877551020409"
\end{verbatim}

\begin{verbatim}
## [1] "t statistic:  98.482504922339"
\end{verbatim}

\begin{verbatim}
## [1] "p_value:  5.46091695562009e-58"
\end{verbatim}

\begin{quote}
\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  She rejected her null hypothesis. TRUE The population mean is well
  outside the critical value range.
\end{enumerate}
\end{quote}

\begin{quote}
\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  The \emph{t}-statistic based on her sample was greater than 2.01. TRUE
  This is relevant given the critical value above.
\end{enumerate}
\end{quote}

\begin{quote}
\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  The \emph{p} value for her \emph{t}-statistic was less than her
  \(\alpha\)-level. TRUE
\end{enumerate}
\end{quote}

\begin{quote}
\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Her degrees of freedom were 51. FALSE
\end{enumerate}
\end{quote}

\begin{quote}
\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Her sample mean of \emph{X} was 9.664. TRUE
\end{enumerate}
\end{quote}

\begin{quote}
\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Her sample mean of \emph{X} was 5.664. FALSE
\end{enumerate}
\end{quote}

\newpage

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Suppose that the readings of a laboratory scale are normally
  distributed with unknown mean \(\mu\) and standard deviation
  \(\sigma\) = 0.01 grams. To assess the accuracy of the laboratory
  scale, a standard weight that is known to weigh exactly 1 gram is
  repeatedly weighed a total of \emph{N} = 50 times. Let \(\bar{x}\) =
  0.998 be the average of the 50 readings. What is the 95\% confidence
  interval for \(\mu\)?
\end{enumerate}

Answer

Here we want to generate a 95\% confidence interval estimated for an
unknown poputation mean. This means that there is a 95\% probability
that the confidence interval will contain the true population mean. As
this is a normal population, and we know the standard deviation, we can
use qnorm(0.975) to find the critical value for a normal distribution.
Using qt(0.975,49) to find the critical value for a t-distribution is a
more conservative approach, but will result in a slightly wider
interval.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n <-}\StringTok{  }\DecValTok{50}
\NormalTok{x_bar <-}\StringTok{ }\FloatTok{0.998}
\NormalTok{sd <-}\StringTok{ }\FloatTok{0.01}

\NormalTok{mult_norm <-}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{)}
\NormalTok{lower_norm <-}\StringTok{ }\NormalTok{x_bar }\OperatorTok{-}\StringTok{ }\NormalTok{(mult_norm}\OperatorTok{*}\NormalTok{(sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n)))}
\NormalTok{upper_norm <-}\StringTok{ }\NormalTok{x_bar }\OperatorTok{+}\StringTok{ }\NormalTok{(mult_norm}\OperatorTok{*}\NormalTok{(sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n)))}
\KeywordTok{paste}\NormalTok{(}\StringTok{"Using the normal distribution: "}\NormalTok{, }\KeywordTok{round}\NormalTok{(lower_norm,}\DecValTok{5}\NormalTok{), }\StringTok{" < mu < "}\NormalTok{ , }\KeywordTok{round}\NormalTok{(upper_norm,}\DecValTok{5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Using the normal distribution:  0.99523  < mu <  1.00077"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# "0.99523  < mu <  1.00077"}

\NormalTok{mult_t    <-}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{,n}\OperatorTok{-}\DecValTok{1}\NormalTok{)}
\NormalTok{lower_t <-}\StringTok{ }\NormalTok{x_bar }\OperatorTok{-}\StringTok{ }\NormalTok{(mult_t}\OperatorTok{*}\NormalTok{(sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n)))}
\NormalTok{upper_t <-}\StringTok{ }\NormalTok{x_bar }\OperatorTok{+}\StringTok{ }\NormalTok{(mult_t}\OperatorTok{*}\NormalTok{(sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n)))}
\KeywordTok{paste}\NormalTok{(}\StringTok{"Using the t-distribution: "}\NormalTok{, }\KeywordTok{round}\NormalTok{(lower_t,}\DecValTok{5}\NormalTok{), }\StringTok{" < mu < "}\NormalTok{ , }\KeywordTok{round}\NormalTok{(upper_t,}\DecValTok{5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Using the t-distribution:  0.99516  < mu <  1.00084"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# "0.99516  < mu <  1.00084"}
\end{Highlighting}
\end{Shaded}


\end{document}
