---
title: "Papers Selected"
output: 
  html_document:
  code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl) #reading in excel files
library(dplyr) #coalesce
library(tidyr) #spread
library(knitr) #kable
library(kableExtra) #add_header
```

```{r include=FALSE}
data_source <- here::here("project", "P0-pick-papers", "PaperChoices.xlsx")
sheets <- excel_sheets(data_source)
paper_data <- read_excel(data_source,sheets[1])
paper_data_cleaned <- paper_data %>%  
    mutate(Study = paste0("<a href='", Paper, "'>", Study, "</a>")) %>% 
    mutate(RepoLink = paste0("<a href='", RepoLink, "'>Data Repo Link</a>")) %>% 
  select(PaperNum, Study, RepoLink)
  
groups <- read_excel(data_source,sheets[2])
choices <- read_excel(data_source,sheets[3])
comb_choices <- left_join(paper_data_cleaned, choices)
comb_choices<- replace_na(comb_choices,list(Groups=0, Preference=0))

```


# Picks so far....
```{r}
comb_table <- comb_choices %>%
  group_by(Study, RepoLink, Preference) %>%
  summarise(n=n()) %>%
  spread(Preference, n)%>%
  select(-`0`)

options(knitr.kable.NA = '')
kab_table <- kable(comb_table, format="html", escape = FALSE)
add_header_above(kab_table, c(" " = 2,"Preference (counts)" = 3)) %>% 
    kable_styling(bootstrap_options = c("hover", "condensed"))
```
## Groups
```{r}
#group_table <- groups %>%
#  group_by(Group) 

# options(knitr.kable.NA = '')
# kab_table <- kable(groups, align = c('l','c'))
# collapse_rows(kab_table, columns = 1)

options(knitr.kable.NA = '')
groups %>% 
  kable(align = c('l','c')) %>% 
  collapse_rows(columns = 1) %>% 
  kable_styling()

```
